// <auto-generated />
using System;
using API_healthyMind.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_healthyMind.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("API_healthyMind.Models.Aprendiz", b =>
                {
                    b.Property<int>("AprCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("apr_codigo")
                        .HasComment("Codigo unico del aprendiz");

                    b.Property<string>("AprAcudApellido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_acud_apellido")
                        .HasComment("apelldio del acudiente");

                    b.Property<string>("AprAcudNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_acud_nombre")
                        .HasComment("Nombre del acudiente");

                    b.Property<string>("AprApellido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_apellido")
                        .HasComment("Apellido del aprendiz");

                    b.Property<int?>("AprCiudadFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("apr_ciudadFK");

                    b.Property<string>("AprCorreoInstitucional")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_correo_institucional");

                    b.Property<string>("AprCorreoPersonal")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_correo_personal")
                        .HasComment("Correo del aprendiz");

                    b.Property<string>("AprDireccion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_direccion");

                    b.Property<string>("AprEps")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_eps");

                    b.Property<int?>("AprEstadoAprFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("apr_estado_aprFK");

                    b.Property<string>("AprEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("apr_estado_registro")
                        .HasDefaultValueSql("'activo'")
                        .HasComment("Estado del registro");

                    b.Property<DateTime>("AprFechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("apr_fechacreacion");

                    b.Property<DateTime?>("AprFechaEliminacion")
                        .HasColumnType("datetime")
                        .HasColumnName("apr_fecha_eliminacion");

                    b.Property<DateOnly?>("AprFechaNac")
                        .HasColumnType("date")
                        .HasColumnName("apr_fechaNac");

                    b.Property<byte[]>("AprFirma")
                        .HasColumnType("blob")
                        .HasColumnName("apr_firma");

                    b.Property<string>("AprNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_nombre")
                        .HasComment("Nombre del aprendiz");

                    b.Property<string>("AprNroDocumento")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("apr_nro_documento")
                        .HasComment("Numero de documento");

                    b.Property<string>("AprPassword")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_password");

                    b.Property<string>("AprPatologia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_patologia");

                    b.Property<string>("AprRazonEliminacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("apr_razon_eliminacion");

                    b.Property<string>("AprSegundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_segundo_apellido")
                        .HasComment("Segundo Apellido");

                    b.Property<string>("AprSegundoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apr_segundo_nombre")
                        .HasComment("Segundo nombre del aprendiz");

                    b.Property<string>("AprTelefono")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("apr_telefono")
                        .HasComment("Numero de celular");

                    b.Property<string>("AprTelefonoAcudiente")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("apr_telefono_acudiente")
                        .HasComment("Numero de celular de un acudiente");

                    b.Property<string>("AprTipoDocumento")
                        .HasColumnType("enum('CC','TI','CE')")
                        .HasColumnName("apr_tipo_documento")
                        .HasComment("Tipo de documento de identidad");

                    b.Property<string>("AprTipoPoblacion")
                        .HasColumnType("enum('Desplazado','Negro','Discapacitado','Campesino','Afro','Gitano','Indigena','Ninguno')")
                        .HasColumnName("apr_tipo_poblacion");

                    b.HasKey("AprCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AprCiudadFk" }, "apr_ciudadFK");

                    b.HasIndex(new[] { "AprEstadoAprFk" }, "apr_estado_aprFK");

                    b.ToTable("aprendiz", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.AprendizFicha", b =>
                {
                    b.Property<int>("AprFicCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("apr_fic_codigo");

                    b.Property<int?>("AprFicAprendizFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("apr_fic_aprendizFK");

                    b.Property<string>("AprFicEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("apr_fic_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.Property<int?>("AprFicFichaFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("apr_fic_fichaFK");

                    b.HasKey("AprFicCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AprFicAprendizFk" }, "apr_fic_aprendizFK");

                    b.HasIndex(new[] { "AprFicCodigo" }, "apr_fic_codigo");

                    b.HasIndex(new[] { "AprFicFichaFk" }, "apr_fic_fichaFK");

                    b.ToTable("aprendiz_ficha", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Area", b =>
                {
                    b.Property<int>("AreaCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("area_codigo")
                        .HasComment("Identificador de la facultad o area");

                    b.Property<string>("AreaEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("area_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.Property<string>("AreaNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("area_nombre")
                        .HasComment("Nombre de la facultad o area");

                    b.Property<int?>("AreaPsicCodFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("area_psic_codFK");

                    b.HasKey("AreaCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AreaPsicCodFk" }, "area_psic_codFK");

                    b.ToTable("area", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.CardsInfo", b =>
                {
                    b.Property<int?>("carCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("car_codigo");

                    b.Property<string>("carDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("car_descripcion");

                    b.Property<string>("carEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("car_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.Property<string>("carLink")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("car_link");

                    b.Property<string>("carTitulo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("car_titulo");

                    b.HasKey("carCodigo")
                        .HasName("PRIMARY");

                    b.ToTable("cards_info", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.CategoriaPreguntas", b =>
                {
                    b.Property<int>("CatPregCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("cat_preg_codigo");

                    b.Property<string>("CatPregDescripcion")
                        .HasColumnType("text")
                        .HasColumnName("cat_preg_descripcion");

                    b.Property<string>("CatPregNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cat_preg_nombre");

                    b.HasKey("CatPregCodigo")
                        .HasName("PRIMARY");

                    b.ToTable("categoria_pregunta", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.CategoriaRespuestas", b =>
                {
                    b.Property<int>("CatResCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("cat_res_codigo");

                    b.Property<string>("CatResDescripcion")
                        .HasColumnType("text")
                        .HasColumnName("cat_res_descripcion");

                    b.Property<string>("CatResNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cat_res_nombre");

                    b.HasKey("CatResCodigo")
                        .HasName("PRIMARY");

                    b.ToTable("categoria_respuesta", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Centro", b =>
                {
                    b.Property<int>("CenCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("cen_codigo")
                        .HasComment("identificador del centro");

                    b.Property<int?>("CenCodFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("cen_codFK");

                    b.Property<string>("CenDireccion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cen_direccion")
                        .HasComment("direccion del centro");

                    b.Property<string>("CenEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("cen_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.Property<string>("CenNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cen_nombre")
                        .HasComment("nombre del centro");

                    b.Property<int?>("CenRegCodFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("cen_reg_codFK");

                    b.HasKey("CenCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CenCodFk" }, "cen_codFK");

                    b.HasIndex(new[] { "CenRegCodFk" }, "cen_reg_codFK");

                    b.ToTable("centro", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Cita", b =>
                {
                    b.Property<int>("CitCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("cit_codigo")
                        .HasComment("Identificador de la cita");

                    b.Property<string>("CitAnotaciones")
                        .HasColumnType("text")
                        .HasColumnName("cit_anotaciones")
                        .HasComment("Anotaciones u observaciones antes o despues de la atencio");

                    b.Property<int?>("CitAprCodFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("cit_apr_codFK")
                        .HasComment("Aprendiz");

                    b.Property<string>("CitEstadoCita")
                        .HasColumnType("enum('programada','realizada','cancelada','reprogramada','no asistió')")
                        .HasColumnName("cit_estado_cita")
                        .HasComment("estado de la cita");

                    b.Property<string>("CitEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("cit_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.Property<DateTime?>("CitFechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("cit_fecha_creacion")
                        .HasComment("fecha en la que se realizo el registro de la cita");

                    b.Property<DateOnly?>("CitFechaProgramada")
                        .HasColumnType("date")
                        .HasColumnName("cit_fecha_programada")
                        .HasComment("Fecha en la que fue programada la cita");

                    b.Property<TimeOnly?>("CitHoraFin")
                        .HasColumnType("time")
                        .HasColumnName("cit_hora_fin")
                        .HasComment("Hora de fin de la cita");

                    b.Property<TimeOnly?>("CitHoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("cit_hora_inicio")
                        .HasComment("Hora de inicio de la cita");

                    b.Property<string>("CitMotivo")
                        .HasColumnType("text")
                        .HasColumnName("cit_motivo")
                        .HasComment("Motivo de la cita");

                    b.Property<string>("CitMotivoSolicitud")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("cit_motivo_solicitud");

                    b.Property<int?>("CitPsiCodFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("cit_psi_codFK")
                        .HasComment("Psicologo");

                    b.Property<string>("CitTipoCita")
                        .HasColumnType("enum('videollamada','chat','presencial')")
                        .HasColumnName("cit_tipo_cita")
                        .HasComment("Tipo de cita");

                    b.HasKey("CitCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CitAprCodFk" }, "cit_apr_codFK");

                    b.HasIndex(new[] { "CitPsiCodFk" }, "cit_psi_codFK");

                    b.ToTable("citas", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Ciudad", b =>
                {
                    b.Property<int>("CiuCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("ciu_codigo");

                    b.Property<string>("CiuNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ciu_nombre");

                    b.Property<int?>("CiuRegionalFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("ciu_regionalFK");

                    b.HasKey("CiuCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CiuRegionalFk" }, "ciu_regionalFK");

                    b.ToTable("ciudad", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Diario", b =>
                {
                    b.Property<int>("DiaCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("dia_codigo");

                    b.Property<int>("DiaAprendizFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("dia_aprendizFK");

                    b.Property<string>("DiaEstadoRegistro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("dia_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.Property<DateOnly?>("DiaFechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("dia_fecha_creacion");

                    b.Property<string>("DiaTitulo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dia_titulo");

                    b.HasKey("DiaCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DiaAprendizFk" }, "dia_aprendizFK");

                    b.ToTable("diario", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Emociones", b =>
                {
                    b.Property<int>("EmoCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("emo_codigo")
                        .HasComment("identificador de la emocion");

                    b.Property<string>("EmoDescripcion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("emo_descripcion")
                        .HasComment("descripcion de la emocion");

                    b.Property<string>("EmoImage")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("emo_image")
                        .HasComment("url de la imagen de la emocion");

                    b.Property<string>("EmoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("emo_nombre")
                        .HasComment("nombre de la emocion");

                    b.HasKey("EmoCodigo")
                        .HasName("PRIMARY");

                    b.ToTable("emociones", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.EstadoAprendiz", b =>
                {
                    b.Property<int>("EstAprCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("est_apr_codigo")
                        .HasComment("Identificador del estado");

                    b.Property<string>("EstAprDescrip")
                        .HasColumnType("text")
                        .HasColumnName("est_apr_descrip")
                        .HasComment("Descripcion del estado");

                    b.Property<string>("EstAprNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("est_apr_nombre")
                        .HasComment("Nombre del estado");

                    b.HasKey("EstAprCodigo")
                        .HasName("PRIMARY");

                    b.ToTable("estado_aprendiz", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Ficha", b =>
                {
                    b.Property<int>("FicCodigo")
                        .HasColumnType("int(40)")
                        .HasColumnName("fic_codigo")
                        .HasComment("Numero de ficha");

                    b.Property<string>("FicEstadoFormacion")
                        .HasColumnType("enum('en ejecucion','cancelada','terminada por fecha','terminada')")
                        .HasColumnName("fic_estado_formacion")
                        .HasComment("Estado de formacion de la ficha");

                    b.Property<string>("FicEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("fic_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.Property<DateOnly?>("FicFechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fic_fecha_fin");

                    b.Property<DateOnly?>("FicFechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fic_fecha_inicio");

                    b.Property<string>("FicJornada")
                        .HasColumnType("enum('diurna','nocturna','madrugada','mixta')")
                        .HasColumnName("fic_jornada")
                        .HasComment("Tipo de jornada de la ficha");

                    b.Property<int?>("FicProgramaFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("fic_programaFK");

                    b.HasKey("FicCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FicProgramaFk" }, "fic_programaFK");

                    b.ToTable("ficha", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.NivelFormacion", b =>
                {
                    b.Property<int>("NivForCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("niv_for_codigo")
                        .HasComment("Identificador del tipo de formacion");

                    b.Property<string>("NivForDescripcion")
                        .HasColumnType("text")
                        .HasColumnName("niv_for_descripcion")
                        .HasComment("Descripcion del tipo de formacion");

                    b.Property<string>("NivForNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("niv_for_nombre")
                        .HasComment("Nombre del tipo de formacion");

                    b.HasKey("NivForCodigo")
                        .HasName("PRIMARY");

                    b.ToTable("nivel_formacion", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.PaginaDiario", b =>
                {
                    b.Property<int>("PagCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("pag_codigo");

                    b.Property<string>("PagContenido")
                        .HasColumnType("text")
                        .HasColumnName("pag_contenido");

                    b.Property<int?>("PagDiarioFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("pag_diarioFK");

                    b.Property<int?>("PagEmocionFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("pag_emocionFK");

                    b.Property<string>("PagEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("pag_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.Property<DateTime>("PagFechaRealizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("pag_fecha_realizacion");

                    b.Property<string>("PagTitulo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pag_titulo");

                    b.HasKey("PagCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PagDiarioFk" }, "pag_diarioFK");

                    b.HasIndex(new[] { "PagEmocionFk" }, "pag_emocionFK");

                    b.ToTable("pagina_diario", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Preguntas", b =>
                {
                    b.Property<int>("PregCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("preg_codigo");

                    b.Property<int?>("PregCategoriaFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("preg_categoriaFK");

                    b.Property<string>("PregDescripcion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("preg_descripcion");

                    b.Property<string>("PregEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("preg_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.HasKey("PregCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PregCategoriaFk" }, "preg_categoriaFK");

                    b.ToTable("pregunta", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Programaformacion", b =>
                {
                    b.Property<int>("ProgCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("prog_codigo")
                        .HasComment("Codigo o identificador del programa de formacion");

                    b.Property<int?>("ProgAreaFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("prog_areaFK");

                    b.Property<int?>("ProgCentroFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("prog_centroFK");

                    b.Property<string>("ProgEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("prog_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.Property<string>("ProgFormaModalidad")
                        .HasColumnType("enum('presencial','virtual','a distancia')")
                        .HasColumnName("prog_forma_modalidad")
                        .HasComment("Tipo de modalidad de formacion");

                    b.Property<string>("ProgModalidad")
                        .HasColumnType("enum('titulada','complementaria')")
                        .HasColumnName("prog_modalidad")
                        .HasComment("Modalidad del programa");

                    b.Property<int?>("ProgNivFormFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("prog_niv_formFK");

                    b.Property<string>("ProgNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("prog_nombre")
                        .HasComment("Nombre del programa");

                    b.HasKey("ProgCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProgAreaFk" }, "prog_areaFK");

                    b.HasIndex(new[] { "ProgCentroFk" }, "prog_centroFK");

                    b.HasIndex(new[] { "ProgNivFormFk" }, "prog_niv_formFK");

                    b.ToTable("programaformacion", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Psicologo", b =>
                {
                    b.Property<int>("PsiCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("psi_codigo")
                        .HasComment("identificador del psicologo");

                    b.Property<string>("PsiApellido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("psi_apellido")
                        .HasComment("Apellido del psicologo");

                    b.Property<string>("PsiCorreoInstitucional")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("psi_correo_institucional")
                        .HasComment("correo institucional");

                    b.Property<string>("PsiCorreoPersonal")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("psi_correo_personal")
                        .HasComment("correo del psicologo");

                    b.Property<string>("PsiDireccion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("psi_direccion")
                        .HasComment("ubicacion de su oficina de trabajo");

                    b.Property<string>("PsiDocumento")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("psi_documento")
                        .HasComment("documento del psicologo");

                    b.Property<string>("PsiEspecialidad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("psi_especialidad")
                        .HasComment("especialidad del psicologo");

                    b.Property<string>("PsiEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo','suspendido')")
                        .HasColumnName("psi_estado_registro")
                        .HasDefaultValueSql("'activo'")
                        .HasComment("estado del psicologo");

                    b.Property<DateOnly?>("PsiFechaNac")
                        .HasColumnType("date")
                        .HasColumnName("psi_fecha_nac")
                        .HasComment("Fecha de nacimiento");

                    b.Property<DateTime?>("PsiFechaRegistro")
                        .HasColumnType("datetime")
                        .HasColumnName("psi_fecha_registro")
                        .HasComment("Fecha en la que se le hizo el registro");

                    b.Property<byte[]>("PsiFirma")
                        .HasColumnType("blob")
                        .HasColumnName("psi_firma");

                    b.Property<string>("PsiNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("psi_nombre")
                        .HasComment("Nombre del psicologo");

                    b.Property<string>("PsiPassword")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("psi_password")
                        .HasComment("contraseña del psicologo");

                    b.Property<string>("PsiTelefono")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("psi_telefono")
                        .HasComment("Numero de telefono del psicologo");

                    b.HasKey("PsiCodigo")
                        .HasName("PRIMARY");

                    b.ToTable("psicologo", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Regional", b =>
                {
                    b.Property<int>("RegCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("reg_codigo")
                        .HasComment("identificador del regional");

                    b.Property<string>("RegEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("reg_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.Property<string>("RegNombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reg_nombre")
                        .HasComment("nombre del regional");

                    b.HasKey("RegCodigo")
                        .HasName("PRIMARY");

                    b.ToTable("regional", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Respuestas", b =>
                {
                    b.Property<int>("ResCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("res_codigo");

                    b.Property<int?>("ResCategoriaFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("res_categoriaFK");

                    b.Property<string>("ResDescripcion")
                        .HasColumnType("text")
                        .HasColumnName("res_descripcion");

                    b.Property<string>("ResEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("res_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.HasKey("ResCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ResCategoriaFk" }, "res_categoriaFK");

                    b.ToTable("respuesta", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.SeguimientoAprendiz", b =>
                {
                    b.Property<int>("SegCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("seg_codigo")
                        .HasComment("Identificador del seguimiento");

                    b.Property<int?>("SegAprendizFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("seg_aprendizFK")
                        .HasComment("Aprendiz");

                    b.Property<string>("SegAreaRemitido")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("seg_area_remitido");

                    b.Property<string>("SegDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("seg_descripcion")
                        .HasComment("Descripcion u observacion al aprendiz");

                    b.Property<string>("SegEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("seg_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.Property<DateTime?>("SegFechaFin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("seg_fecha_fin")
                        .HasComment("Fecha final del seguimiento");

                    b.Property<DateTime?>("SegFechaSeguimiento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("seg_fecha_seguimiento")
                        .HasComment("Fecha de inicio del seguimiento");

                    b.Property<string>("SegFirmaAprendiz")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("seg_firma_aprendiz");

                    b.Property<string>("SegFirmaProfesional")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("seg_firma_profesional");

                    b.Property<string>("SegMotivo")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("seg_motivo");

                    b.Property<int?>("SegPsicologoFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("seg_psicologoFK")
                        .HasComment("Psicologo");

                    b.Property<string>("SegRecomendaciones")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("seg_recomendaciones")
                        .HasComment("recomendaciones para el aprendiz");

                    b.Property<int?>("SegTrimestreActual")
                        .HasColumnType("int(11)")
                        .HasColumnName("seg_trimestre_actual");

                    b.HasKey("SegCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SegPsicologoFk" }, "seg_psicologoFK");

                    b.HasIndex(new[] { "SegAprendizFk" }, "seguimiento_aprendiz_ibfk_2");

                    b.ToTable("seguimiento_aprendiz", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.TestGeneral", b =>
                {
                    b.Property<int>("TestGenCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(40)")
                        .HasColumnName("test_gen_codigo");

                    b.Property<int?>("TestGenApreFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("test_gen_apreFK");

                    b.Property<string>("TestGenEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("test_gen_estado")
                        .HasDefaultValueSql("'activo'");

                    b.Property<DateTime?>("TestGenFechaRealiz")
                        .HasColumnType("datetime")
                        .HasColumnName("test_gen_fecha_realiz");

                    b.Property<int?>("TestGenPsicoFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("test_gen_psicoFK");

                    b.Property<string>("TestGenRecomendacion")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("test_gen_recomendacion");

                    b.Property<string>("TestGenResultados")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("test_gen_resultados");

                    b.HasKey("TestGenCodigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TestGenApreFk" }, "reg_test_apreFK");

                    b.HasIndex(new[] { "TestGenPsicoFk" }, "test_gen_psicoFK");

                    b.ToTable("test_general", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.TestPreguntas", b =>
                {
                    b.Property<int>("TesRegistroFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("tes_registroFK");

                    b.Property<int>("TesPregFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("tes_pregFK");

                    b.Property<int>("TesRespFk")
                        .HasColumnType("int(40)")
                        .HasColumnName("tes_respFK");

                    b.Property<string>("TesEstadoRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('activo','inactivo')")
                        .HasColumnName("tes_estado_registro")
                        .HasDefaultValueSql("'activo'");

                    b.HasKey("TesRegistroFk", "TesPregFk", "TesRespFk")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0 });

                    b.HasIndex(new[] { "TesPregFk" }, "tes_pregFK");

                    b.HasIndex(new[] { "TesRegistroFk", "TesPregFk", "TesRespFk" }, "tes_registroFK");

                    b.HasIndex(new[] { "TesRespFk" }, "tes_respFK");

                    b.ToTable("test_pregunta", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.VerificationCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int?>("AprendizId")
                        .HasColumnType("int(11)")
                        .HasColumnName("AprendizId");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("Codigo");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime")
                        .HasColumnName("Expiration");

                    b.Property<int?>("PsicologoId")
                        .HasColumnType("int(11)")
                        .HasColumnName("PsicologoId");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AprendizId" }, "AprendizId");

                    b.HasIndex(new[] { "PsicologoId" }, "PsicologoId");

                    b.ToTable("verificationcode", (string)null);
                });

            modelBuilder.Entity("API_healthyMind.Models.Aprendiz", b =>
                {
                    b.HasOne("API_healthyMind.Models.Ciudad", "Municipio")
                        .WithMany("Aprendizs")
                        .HasForeignKey("AprCiudadFk")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("aprendiz_ibfk_2");

                    b.HasOne("API_healthyMind.Models.EstadoAprendiz", "EstadoAprendiz")
                        .WithMany("Aprendizs")
                        .HasForeignKey("AprEstadoAprFk")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("aprendiz_ibfk_1");

                    b.Navigation("EstadoAprendiz");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("API_healthyMind.Models.AprendizFicha", b =>
                {
                    b.HasOne("API_healthyMind.Models.Aprendiz", "Aprendiz")
                        .WithMany("AprendizFichas")
                        .HasForeignKey("AprFicAprendizFk")
                        .HasConstraintName("aprendiz_ficha_ibfk_2");

                    b.HasOne("API_healthyMind.Models.Ficha", "Ficha")
                        .WithMany("AprendizFichas")
                        .HasForeignKey("AprFicFichaFk")
                        .HasConstraintName("aprendiz_ficha_ibfk_1");

                    b.Navigation("Aprendiz");

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("API_healthyMind.Models.Area", b =>
                {
                    b.HasOne("API_healthyMind.Models.Psicologo", "AreaPsicologo")
                        .WithMany("Area")
                        .HasForeignKey("AreaPsicCodFk")
                        .HasConstraintName("area_ibfk_1");

                    b.Navigation("AreaPsicologo");
                });

            modelBuilder.Entity("API_healthyMind.Models.Centro", b =>
                {
                    b.HasOne("API_healthyMind.Models.Centro", "centroPadre")
                        .WithMany("InverseCenCodFkNavigation")
                        .HasForeignKey("CenCodFk")
                        .HasConstraintName("centro_ibfk_2");

                    b.HasOne("API_healthyMind.Models.Regional", "Regional")
                        .WithMany("Centros")
                        .HasForeignKey("CenRegCodFk")
                        .HasConstraintName("centro_ibfk_1");

                    b.Navigation("Regional");

                    b.Navigation("centroPadre");
                });

            modelBuilder.Entity("API_healthyMind.Models.Cita", b =>
                {
                    b.HasOne("API_healthyMind.Models.AprendizFicha", "CitAprCodFkNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("CitAprCodFk")
                        .HasConstraintName("citas_ibfk_3");

                    b.HasOne("API_healthyMind.Models.Psicologo", "CitPsiCodFkNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("CitPsiCodFk")
                        .HasConstraintName("citas_ibfk_2");

                    b.Navigation("CitAprCodFkNavigation");

                    b.Navigation("CitPsiCodFkNavigation");
                });

            modelBuilder.Entity("API_healthyMind.Models.Ciudad", b =>
                {
                    b.HasOne("API_healthyMind.Models.Regional", "Regional")
                        .WithMany("Ciudads")
                        .HasForeignKey("CiuRegionalFk")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("ciudad_ibfk_1");

                    b.Navigation("Regional");
                });

            modelBuilder.Entity("API_healthyMind.Models.Diario", b =>
                {
                    b.HasOne("API_healthyMind.Models.Aprendiz", "aprendiz")
                        .WithMany("Diarios")
                        .HasForeignKey("DiaAprendizFk")
                        .IsRequired()
                        .HasConstraintName("diario_ibfk_1");

                    b.Navigation("aprendiz");
                });

            modelBuilder.Entity("API_healthyMind.Models.Ficha", b =>
                {
                    b.HasOne("API_healthyMind.Models.Programaformacion", "programaFormacion")
                        .WithMany("Fichas")
                        .HasForeignKey("FicProgramaFk")
                        .HasConstraintName("ficha_ibfk_1");

                    b.Navigation("programaFormacion");
                });

            modelBuilder.Entity("API_healthyMind.Models.PaginaDiario", b =>
                {
                    b.HasOne("API_healthyMind.Models.Diario", "PagDiarioFkNavigation")
                        .WithMany("PaginaDiarios")
                        .HasForeignKey("PagDiarioFk")
                        .HasConstraintName("pagina_diario_ibfk_2");

                    b.HasOne("API_healthyMind.Models.Emociones", "PagEmocionFkNavigation")
                        .WithMany("PaginaDiarios")
                        .HasForeignKey("PagEmocionFk")
                        .HasConstraintName("pagina_diario_ibfk_1");

                    b.Navigation("PagDiarioFkNavigation");

                    b.Navigation("PagEmocionFkNavigation");
                });

            modelBuilder.Entity("API_healthyMind.Models.Preguntas", b =>
                {
                    b.HasOne("API_healthyMind.Models.CategoriaPreguntas", "CategoriaPregunta")
                        .WithMany("Pregunta")
                        .HasForeignKey("PregCategoriaFk")
                        .HasConstraintName("pregunta_ibfk_1");

                    b.Navigation("CategoriaPregunta");
                });

            modelBuilder.Entity("API_healthyMind.Models.Programaformacion", b =>
                {
                    b.HasOne("API_healthyMind.Models.Area", "Area")
                        .WithMany("Programaformacions")
                        .HasForeignKey("ProgAreaFk")
                        .HasConstraintName("programaformacion_ibfk_3");

                    b.HasOne("API_healthyMind.Models.Centro", "Centro")
                        .WithMany("Programaformacions")
                        .HasForeignKey("ProgCentroFk")
                        .HasConstraintName("programaformacion_ibfk_1");

                    b.HasOne("API_healthyMind.Models.NivelFormacion", "NivelFormacion")
                        .WithMany("Programaformacions")
                        .HasForeignKey("ProgNivFormFk")
                        .HasConstraintName("programaformacion_ibfk_2");

                    b.Navigation("Area");

                    b.Navigation("Centro");

                    b.Navigation("NivelFormacion");
                });

            modelBuilder.Entity("API_healthyMind.Models.Respuestas", b =>
                {
                    b.HasOne("API_healthyMind.Models.CategoriaRespuestas", "CategoriaRespuesta")
                        .WithMany("Respuesta")
                        .HasForeignKey("ResCategoriaFk")
                        .HasConstraintName("respuesta_ibfk_1");

                    b.Navigation("CategoriaRespuesta");
                });

            modelBuilder.Entity("API_healthyMind.Models.SeguimientoAprendiz", b =>
                {
                    b.HasOne("API_healthyMind.Models.AprendizFicha", "SegAprendizFkNavigation")
                        .WithMany("SeguimientoAprendizs")
                        .HasForeignKey("SegAprendizFk")
                        .HasConstraintName("seguimiento_aprendiz_ibfk_4");

                    b.HasOne("API_healthyMind.Models.Psicologo", "SegPsicologoFkNavigation")
                        .WithMany("SeguimientoAprendizs")
                        .HasForeignKey("SegPsicologoFk")
                        .HasConstraintName("seguimiento_aprendiz_ibfk_3");

                    b.Navigation("SegAprendizFkNavigation");

                    b.Navigation("SegPsicologoFkNavigation");
                });

            modelBuilder.Entity("API_healthyMind.Models.TestGeneral", b =>
                {
                    b.HasOne("API_healthyMind.Models.AprendizFicha", "TestGenApreFkNavigation")
                        .WithMany("TestGenerals")
                        .HasForeignKey("TestGenApreFk")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("test_general_ibfk_1");

                    b.HasOne("API_healthyMind.Models.Psicologo", "TestGenPsicoFkNavigation")
                        .WithMany("TestGenerals")
                        .HasForeignKey("TestGenPsicoFk")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("test_general_ibfk_2");

                    b.Navigation("TestGenApreFkNavigation");

                    b.Navigation("TestGenPsicoFkNavigation");
                });

            modelBuilder.Entity("API_healthyMind.Models.TestPreguntas", b =>
                {
                    b.HasOne("API_healthyMind.Models.Preguntas", "TesPregFkNavigation")
                        .WithMany("TestPregunta")
                        .HasForeignKey("TesPregFk")
                        .IsRequired()
                        .HasConstraintName("test_pregunta_ibfk_1");

                    b.HasOne("API_healthyMind.Models.TestGeneral", "TesRegistroFkNavigation")
                        .WithMany("TestPregunta")
                        .HasForeignKey("TesRegistroFk")
                        .IsRequired()
                        .HasConstraintName("test_pregunta_ibfk_3");

                    b.HasOne("API_healthyMind.Models.Respuestas", "TesRespFkNavigation")
                        .WithMany("TestPregunta")
                        .HasForeignKey("TesRespFk")
                        .IsRequired()
                        .HasConstraintName("test_pregunta_ibfk_2");

                    b.Navigation("TesPregFkNavigation");

                    b.Navigation("TesRegistroFkNavigation");

                    b.Navigation("TesRespFkNavigation");
                });

            modelBuilder.Entity("API_healthyMind.Models.VerificationCode", b =>
                {
                    b.HasOne("API_healthyMind.Models.Aprendiz", "Aprendiz")
                        .WithMany("VerificationCode")
                        .HasForeignKey("AprendizId")
                        .HasConstraintName("verificationcode_ibfk_1");

                    b.HasOne("API_healthyMind.Models.Psicologo", "Psicologo")
                        .WithMany("VerificationCode")
                        .HasForeignKey("PsicologoId")
                        .HasConstraintName("verificationcode_ibfk_2");

                    b.Navigation("Aprendiz");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("API_healthyMind.Models.Aprendiz", b =>
                {
                    b.Navigation("AprendizFichas");

                    b.Navigation("Diarios");

                    b.Navigation("VerificationCode");
                });

            modelBuilder.Entity("API_healthyMind.Models.AprendizFicha", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("SeguimientoAprendizs");

                    b.Navigation("TestGenerals");
                });

            modelBuilder.Entity("API_healthyMind.Models.Area", b =>
                {
                    b.Navigation("Programaformacions");
                });

            modelBuilder.Entity("API_healthyMind.Models.CategoriaPreguntas", b =>
                {
                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("API_healthyMind.Models.CategoriaRespuestas", b =>
                {
                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("API_healthyMind.Models.Centro", b =>
                {
                    b.Navigation("InverseCenCodFkNavigation");

                    b.Navigation("Programaformacions");
                });

            modelBuilder.Entity("API_healthyMind.Models.Ciudad", b =>
                {
                    b.Navigation("Aprendizs");
                });

            modelBuilder.Entity("API_healthyMind.Models.Diario", b =>
                {
                    b.Navigation("PaginaDiarios");
                });

            modelBuilder.Entity("API_healthyMind.Models.Emociones", b =>
                {
                    b.Navigation("PaginaDiarios");
                });

            modelBuilder.Entity("API_healthyMind.Models.EstadoAprendiz", b =>
                {
                    b.Navigation("Aprendizs");
                });

            modelBuilder.Entity("API_healthyMind.Models.Ficha", b =>
                {
                    b.Navigation("AprendizFichas");
                });

            modelBuilder.Entity("API_healthyMind.Models.NivelFormacion", b =>
                {
                    b.Navigation("Programaformacions");
                });

            modelBuilder.Entity("API_healthyMind.Models.Preguntas", b =>
                {
                    b.Navigation("TestPregunta");
                });

            modelBuilder.Entity("API_healthyMind.Models.Programaformacion", b =>
                {
                    b.Navigation("Fichas");
                });

            modelBuilder.Entity("API_healthyMind.Models.Psicologo", b =>
                {
                    b.Navigation("Area");

                    b.Navigation("Cita");

                    b.Navigation("SeguimientoAprendizs");

                    b.Navigation("TestGenerals");

                    b.Navigation("VerificationCode");
                });

            modelBuilder.Entity("API_healthyMind.Models.Regional", b =>
                {
                    b.Navigation("Centros");

                    b.Navigation("Ciudads");
                });

            modelBuilder.Entity("API_healthyMind.Models.Respuestas", b =>
                {
                    b.Navigation("TestPregunta");
                });

            modelBuilder.Entity("API_healthyMind.Models.TestGeneral", b =>
                {
                    b.Navigation("TestPregunta");
                });
#pragma warning restore 612, 618
        }
    }
}
